version: '3'

services: 
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes: 
      - clean-node-api-mongo-db:/data/db
    ports: 
      - '27017:27017'
    networks: 
      - clean-node-api-network
  api:
    container_name: api-container
    image: node:16
    restart: always
    user: '1000'
    working_dir: /usr/src/clean-node-api
    tty: true
    volumes: 
      - ./:/usr/src/clean-node-api/
      - /home/lucasleal/.ssh:/home/node/.ssh
    ports: 
      - '5050:5050'
      - '9222:9222'
    networks: 
      - clean-node-api-network

networks: 
  clean-node-api-network:

volumes: 
  clean-node-api-mongo-db: